title: "[rp-issue] "
labels: ["rp-issue form"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: Issue-description
    attributes:
      label: Describe the problem
      description: "A clear and concise description of the problem faced."
      value: |
        1.
        2.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: textarea
    id: RP info
    attributes:
      label: Provide details about the RP
      description: "Please provide detailed info about the RP hardware (GPU, CPU, etc.) as well as Lilypad version running on the RP."
    validations:
      required: true
