title: "[RP-issue form]"
labels: ["RP support"]
body:
  - type: markdown
    attributes:
      value: |
        ## Issue Submission Form
        Fill out this discussion form below to submit an issue for the team to review! This will be used by our team to keep track of the issue.
  
  - type: textarea
    id: problem_description
    attributes:
      label: Describe the problem
      description: "Describe the problem faced by the RP in order to help speed up support from our team."
      value: "Please describe your issue here..."
    validations:
      required: true

  - type: textarea
    id: rp_info
    attributes:
      label: RP hardware and software info
      description: "Provide info about the hardware used in the RP and lilypad version running"
      value: "Hardware specs:\nLilypad version:"
    validations:
      required: true

  - type: textarea
    id: eth_address
    attributes:
      label: Eth address (Wallet address)
      description: "Provide the ETH (wallet) address for the RP and any relevant on-chain transactions."
      value: "ETH Address:\nRelevant transactions:"
    validations:
      required: true

  - type: textarea
    id: rp_logs
    attributes:
      label: RP logs
      description: "Paste in logs from bacalhau and lilypad-resource-provider"
      value: "Paste your logs here..."
    validations:
      required: true
