title: "[rp-issue] "
labels: ["rp-issue form"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: Issue-description
    attributes:
      label: Describe the problem
      description: "A clear and concise description of the problem faced."
      value: |
        1.
        2.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: textarea
    id: RP info
    attributes:
      label: PRovide details about the RP
      description: "Please provide detailed info about the RP hardware (GPU, CPU, etc.) as well as Lilypad version running on the RP."
    validations:
      required: true
  - type: textarea
    id: Blockchain/Eth address
    attributes:
      label: Which area of this project could be most improved?
       description: "Please include the wallet address for the affected RP and any transaction hashes that are relevant to the problem."
    validations:
      required: true
type: textarea
    id: RP logs
    attributes:
      label: Logs from lilypad-resource-provider and bacalhau
       description: " Please include log outputs from the lilypad-resource-provider and bacalhau."
    validations:
      required: true


      
